import { AdminUser, WithdrawalRequest, AppRate, Country, App, ContentBlock, AuditLog } from './types';

export const mockUsers: AdminUser[] = [
  {
    id: 'user-1',
    name: 'Ahmed Hassan',
    email: 'ahmed@yallacoins.com',
    phone: '+201001234567',
    role: 'super_admin',
    active: true,
    lastLogin: new Date(Date.now() - 30 * 60000).toISOString(),
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Fatima Mohamed',
    email: 'fatima@yallacoins.com',
    phone: '+201009876543',
    role: 'operations_admin',
    active: true,
    lastLogin: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Karim Ibrahim',
    email: 'karim@yallacoins.com',
    phone: '+201005555555',
    role: 'finance_admin',
    active: true,
    lastLogin: new Date(Date.now() - 4 * 60 * 60000).toISOString(),
    createdAt: '2024-02-10T10:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Leila Mansour',
    email: 'leila@yallacoins.com',
    phone: '+201007777777',
    role: 'rate_manager',
    active: true,
    lastLogin: new Date(Date.now() - 1 * 60 * 60000).toISOString(),
    createdAt: '2024-02-15T10:00:00Z',
  },
];

export const mockWithdrawalRequests: WithdrawalRequest[] = [
  {
    id: 'REQ-2024-001',
    creatorId: 'creator-1',
    app: 'bigo',
    accountId: 'bigo_user_12345',
    phone: '+201001234567',
    amountSubmitted: 5000,
    currency: 'beans',
    estimatedUSD: 500,
    estimatedPayout: 4750,
    payoutCurrency: 'EGP',
    country: 'Egypt',
    payoutMethod: 'Vodafone Cash',
    payoutInfo: '201001234567',
    status: 'submitted',
    notes: [],
    financeNotes: [],
    riskTags: [],
    submittedAt: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    rateSnapshot: {
      rate: 0.1,
      fee: 50,
      timestamp: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    },
  },
  {
    id: 'REQ-2024-002',
    creatorId: 'creator-2',
    app: 'kiti',
    accountId: 'kiti_user_67890',
    phone: '+201009876543',
    amountSubmitted: 10000,
    currency: 'points',
    estimatedUSD: 1000,
    estimatedPayout: 9500,
    payoutCurrency: 'EGP',
    country: 'Egypt',
    payoutMethod: 'InstaPay',
    payoutInfo: 'instapay_account_123',
    status: 'under_review',
    assignedTo: 'user-2',
    notes: ['Checking account verification'],
    financeNotes: [],
    riskTags: [],
    submittedAt: new Date(Date.now() - 24 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60000).toISOString(),
    rateSnapshot: {
      rate: 0.1,
      fee: 50,
      timestamp: new Date(Date.now() - 24 * 60 * 60000).toISOString(),
    },
  },
  {
    id: 'REQ-2024-003',
    creatorId: 'creator-3',
    app: 'xena',
    accountId: 'xena_user_11111',
    phone: '+201005555555',
    amountSubmitted: 2500,
    currency: 'coins',
    estimatedUSD: 250,
    estimatedPayout: 2375,
    payoutCurrency: 'AED',
    country: 'UAE',
    payoutMethod: 'Bank Transfer',
    payoutInfo: 'AE123456789012345678',
    status: 'approved',
    assignedTo: 'user-2',
    notes: ['Verified account', 'All documents valid'],
    financeNotes: [],
    riskTags: [],
    submittedAt: new Date(Date.now() - 48 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60000).toISOString(),
    rateSnapshot: {
      rate: 0.1,
      fee: 50,
      timestamp: new Date(Date.now() - 48 * 60 * 60000).toISOString(),
    },
  },
  {
    id: 'REQ-2024-004',
    creatorId: 'creator-4',
    app: 'bigo',
    accountId: 'bigo_user_22222',
    phone: '+201007777777',
    amountSubmitted: 8000,
    currency: 'beans',
    estimatedUSD: 800,
    estimatedPayout: 7600,
    payoutCurrency: 'EGP',
    country: 'Egypt',
    payoutMethod: 'Vodafone Cash',
    payoutInfo: '201007777777',
    status: 'paid',
    assignedTo: 'user-2',
    notes: ['Approved for payout'],
    financeNotes: ['Payout executed via Vodafone', 'Confirmed by recipient'],
    riskTags: [],
    submittedAt: new Date(Date.now() - 72 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60000).toISOString(),
    paidAt: new Date(Date.now() - 6 * 60 * 60000).toISOString(),
    rateSnapshot: {
      rate: 0.1,
      fee: 50,
      timestamp: new Date(Date.now() - 72 * 60 * 60000).toISOString(),
    },
  },
  {
    id: 'REQ-2024-005',
    creatorId: 'creator-5',
    app: 'kiti',
    accountId: 'kiti_user_33333',
    phone: '+201003333333',
    amountSubmitted: 3000,
    currency: 'points',
    estimatedUSD: 300,
    estimatedPayout: 2850,
    payoutCurrency: 'EGP',
    country: 'Egypt',
    payoutMethod: 'Bank Transfer',
    payoutInfo: 'EG1234567890123456789012',
    status: 'needs_correction',
    assignedTo: 'user-2',
    notes: ['IBAN format incorrect', 'Please resubmit with valid IBAN'],
    financeNotes: [],
    riskTags: ['invalid_iban'],
    submittedAt: new Date(Date.now() - 36 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60000).toISOString(),
    rateSnapshot: {
      rate: 0.1,
      fee: 50,
      timestamp: new Date(Date.now() - 36 * 60 * 60000).toISOString(),
    },
  },
];

export const mockAppRates: AppRate[] = [
  {
    id: 'rate-1',
    appName: 'bigo',
    conversionLogic: '1 Bean = $0.10',
    publicRate: 0.1,
    internalRate: 0.095,
    feeType: 'percentage',
    feeValue: 5,
    minimumWithdrawal: 500,
    etaText: '24-48 hours',
    status: 'active',
    publicNote: 'Standard withdrawal processing',
    updatedBy: 'user-4',
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60000).toISOString(),
    versionHistory: [
      {
        version: 1,
        rate: 0.1,
        fee: 5,
        updatedBy: 'user-4',
        updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60000).toISOString(),
        reason: 'Initial rate setup',
      },
    ],
  },
  {
    id: 'rate-2',
    appName: 'kiti',
    conversionLogic: '1 Point = $0.12',
    publicRate: 0.12,
    internalRate: 0.115,
    feeType: 'percentage',
    feeValue: 5,
    minimumWithdrawal: 400,
    etaText: '24-48 hours',
    status: 'active',
    publicNote: 'Standard withdrawal processing',
    updatedBy: 'user-4',
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60000).toISOString(),
    versionHistory: [],
  },
  {
    id: 'rate-3',
    appName: 'xena',
    conversionLogic: '1 Coin = $0.08',
    publicRate: 0.08,
    internalRate: 0.075,
    feeType: 'percentage',
    feeValue: 5,
    minimumWithdrawal: 600,
    etaText: '48-72 hours',
    status: 'active',
    publicNote: 'Standard withdrawal processing',
    updatedBy: 'user-4',
    updatedAt: new Date(Date.now() - 21 * 24 * 60 * 60000).toISOString(),
    versionHistory: [],
  },
];

export const mockCountries: Country[] = [
  {
    id: 'country-1',
    name: 'Egypt',
    code: 'EG',
    currency: 'EGP',
    active: true,
    payoutMethods: [
      {
        id: 'method-1',
        name: 'Vodafone Cash',
        feeType: 'percentage',
        feeValue: 3,
        etaText: '1-2 hours',
        enabled: true,
        recommended: true,
        publicNote: 'Instant delivery',
        internalNote: 'Most popular method',
      },
      {
        id: 'method-2',
        name: 'InstaPay',
        feeType: 'percentage',
        feeValue: 2,
        etaText: '2-4 hours',
        enabled: true,
        recommended: false,
        publicNote: 'Bank transfer via InstaPay',
        internalNote: 'Requires bank account',
      },
      {
        id: 'method-3',
        name: 'Bank Transfer',
        feeType: 'fixed',
        feeValue: 50,
        etaText: '24-48 hours',
        enabled: true,
        recommended: false,
        publicNote: 'Direct bank transfer',
        internalNote: 'Standard banking hours',
      },
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'country-2',
    name: 'UAE',
    code: 'AE',
    currency: 'AED',
    active: true,
    payoutMethods: [
      {
        id: 'method-4',
        name: 'Bank Transfer',
        feeType: 'fixed',
        feeValue: 25,
        etaText: '24-48 hours',
        enabled: true,
        recommended: true,
        publicNote: 'Direct bank transfer',
        internalNote: 'Standard banking hours',
      },
      {
        id: 'method-5',
        name: 'USDT',
        feeType: 'percentage',
        feeValue: 1,
        etaText: '1-2 hours',
        enabled: true,
        recommended: false,
        publicNote: 'Cryptocurrency transfer',
        internalNote: 'Blockchain-based',
      },
    ],
    updatedAt: new Date().toISOString(),
  },
];

export const mockApps: App[] = [
  {
    id: 'app-1',
    name: 'bigo',
    logo: 'https://via.placeholder.com/100',
    status: 'active',
    conversionUnitLabel: 'Beans',
    idHelperText: 'Your Bigo Live account ID (found in wallet settings)',
    uploadInstructions: 'Upload screenshot showing your Bigo Live wallet balance',
    publicMessages: 'Bigo Live withdrawal available',
    internalRules: 'Verify account status before approval',
  },
  {
    id: 'app-2',
    name: 'kiti',
    logo: 'https://via.placeholder.com/100',
    status: 'active',
    conversionUnitLabel: 'Points',
    idHelperText: 'Your Kiti account ID (found in profile settings)',
    uploadInstructions: 'Upload screenshot showing your Kiti account balance',
    publicMessages: 'Kiti withdrawal available',
    internalRules: 'Check account verification status',
  },
  {
    id: 'app-3',
    name: 'xena',
    logo: 'https://via.placeholder.com/100',
    status: 'active',
    conversionUnitLabel: 'Coins',
    idHelperText: 'Your Xena Live account ID (found in wallet)',
    uploadInstructions: 'Upload screenshot showing your Xena Live coins balance',
    publicMessages: 'Xena Live withdrawal available',
    internalRules: 'Verify Xena account authenticity',
  },
];

export const mockContentBlocks: ContentBlock[] = [
  {
    id: 'content-1',
    key: 'hero_headline',
    label: 'Hero Headline',
    value: 'Withdraw Your Earnings Instantly',
    type: 'text',
    updatedBy: 'user-1',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'content-2',
    key: 'hero_subheadline',
    label: 'Hero Subheadline',
    value: 'Fast, secure, and transparent withdrawal process for all creators',
    type: 'text',
    updatedBy: 'user-1',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'content-3',
    key: 'trust_line',
    label: 'Trust Line',
    value: 'Trusted by thousands of creators across the Middle East',
    type: 'text',
    updatedBy: 'user-1',
    updatedAt: new Date().toISOString(),
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
    user: 'user-2',
    actionType: 'status_change',
    entityType: 'withdrawal_request',
    entityId: 'REQ-2024-001',
    oldValue: 'submitted',
    newValue: 'under_review',
    comment: 'Started initial review',
  },
  {
    id: 'log-2',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    user: 'user-1',
    actionType: 'rate_update',
    entityType: 'app_rate',
    entityId: 'rate-1',
    oldValue: '0.095',
    newValue: '0.1',
    comment: 'Adjusted Bigo rate',
  },
  {
    id: 'log-3',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    user: 'user-3',
    actionType: 'mark_paid',
    entityType: 'withdrawal_request',
    entityId: 'REQ-2024-004',
    comment: 'Payout confirmed',
  },
];
